export enum PhishingStatus {
    PHISHING = 'PHISHING',
    LEGITIMATE = 'LEGITIMATE',
    PROCESSING = 'PROCESSING',
    EXTENSION_INITIALIZING = 'EXTENSION_INITIALIZING',
    ERROR = 'ERROR',
    DEEPER_ANALISIS_REQIRED = "DEEPER_ANALISIS_REQIRED",
}